import { ElementDefinition } from '@/core/types';
import { EMPTY_ID } from '@/core/constants';
import { registerElement } from '../registry';
import { createPowderBehavior } from '../behaviors/powder';
import { createLiquidBehavior } from '../behaviors/liquid';
import { createGasBehavior } from '../behaviors/gas';
import { compose } from '../behaviors/composer';
import {
  acidReaction,
  crystalReaction,
  explosiveReaction,
  fireReaction,
  lavaReaction,
  plantReaction,
  radiationBehavior,
  saltReaction,
  sandWetReaction,
  seedReaction,
  sparkReaction,
  uraniumReaction,
  virusReaction,
} from '../behaviors/reactions';
import {
  batteryBehavior,
  clonerBehavior,
  conductorBehavior,
  conductorRenderColor,
  fanBehavior,
  magnetBehavior,
  torchBehavior,
  voidBehavior,
} from '../behaviors/structures';
import {
  antigravityBehavior,
  antimatterBehavior,
  blackHoleBehavior,
  chlorineBehavior,
  co2Behavior,
  geyserBehavior,
  glueBehavior,
  ice9Behavior,
  lightningCloudBehavior,
  lightningRodBehavior,
  mushroomBehavior,
  nanobotBehavior,
  oxygenBehavior,
  poisonReaction,
  portalABehavior,
  portalBBehavior,
  pulseRenderColor,
} from '../behaviors/exotic';

/**
 * Element definitions.
 *
 * IDs are stable integers (never reuse), keys are stable strings.
 * Thermal profiles are declarative — the ThermalEngine reads them and
 * performs state transitions so individual elements stay tiny.
 *
 * Thermal calibration (conductivity values, unitless):
 *
 *   0.220  copper           (best conductor)
 *   0.180  iron, torch, cryo, spark, mercury, lightning rod
 *   0.150  fire, lava, diamond
 *   0.100  uranium, ice-9
 *   0.080  ice, snow, nanobots, antimatter, geyser, crystal
 *   0.045  stone, coal
 *   0.040  water, acid, glass, obsidian, radiation, portals, poison, nitro, napalm
 *   0.030  sand, mud, salt, gunpowder, wick, waxliq, steam, tar
 *   0.020  empty (air), wood, ash, dust, plant, honey, wax, helium, antigravity
 *   0.015  smoke, gas, chlorine, co2, methane, glue, fan, void, storm cloud
 *   0.010  cloner, oxygen
 *   0.005  foam
 *   0.003  rubber         (insulator)
 *   0.002  wall           (insulator)
 */

const defs: ElementDefinition[] = [
  {
    id: EMPTY_ID,
    key: 'empty',
    label: 'Eraser',
    category: 'empty',
    color: 0x0a0a0b,
    density: 0,
    hotkey: 'E',
    description: 'Erase / clear cells.',
    // Air is a *weak* conductor but a *very gentle* sink toward ambient.
    // A strong emit would flatten hot / cold zones within half a second;
    // at 0.0012 the half-life is ~10 seconds which is what the eye reads
    // as "the room is cold", not "a ghost of cold is quickly fading".
    thermal: { conductivity: 0.020, emitTemp: 0, emitStrength: 0.0012, heatCapacity: 0.15 },
  },
  {
    id: 1,
    key: 'wall',
    label: 'Wall',
    category: 'solid',
    color: 0x2a2a2f,
    colorVariance: 6,
    density: 1000,
    hotkey: 'W',
    description: 'Indestructible barrier. Thermally inert.',
    thermal: { conductivity: 0.002, heatCapacity: 5.0 },
  },
  {
    id: 2,
    key: 'stone',
    label: 'Stone',
    category: 'solid',
    color: 0x5a5a62,
    colorVariance: 14,
    density: 900,
    description: 'Hardened rock. Formed when lava meets water.',
    thermal: { conductivity: 0.045, heatCapacity: 3.0 },
  },
  {
    id: 3,
    key: 'sand',
    label: 'Sand',
    category: 'powder',
    color: 0xe5c47a,
    colorVariance: 18,
    density: 60,
    hotkey: 'S',
    description: 'Classic powder. Melts into glass near lava; mixes with water into mud.',
    update: compose(createPowderBehavior(60), sandWetReaction),
    thermal: { conductivity: 0.030, heatCapacity: 2.0 },
  },
  {
    id: 4,
    key: 'water',
    label: 'Water',
    category: 'liquid',
    color: 0x4aa3ff,
    colorVariance: 10,
    density: 30,
    hotkey: 'D',
    description: 'Freezes into ice below -5°, boils into steam above 90°.',
    update: createLiquidBehavior(30, 6),
    thermal: {
      conductivity: 0.060,
      heatCapacity: 3.0,
      freezeAt: -5,
      freezesInto: 'ice',
      boilAt: 90,
      boilsInto: 'steam',
    },
  },
  {
    id: 5,
    key: 'oil',
    label: 'Oil',
    category: 'liquid',
    color: 0x6b4a2a,
    colorVariance: 10,
    density: 20,
    flammable: true,
    burnChance: 0.35,
    hotkey: 'O',
    description: 'Auto-ignites above 55°. Floats on water.',
    update: createLiquidBehavior(20, 4),
    thermal: { conductivity: 0.040, ignitesAt: 55 },
  },
  {
    id: 6,
    key: 'acid',
    label: 'Acid',
    category: 'liquid',
    color: 0x9cff3a,
    colorVariance: 15,
    density: 35,
    hotkey: 'A',
    description: 'Dissolves most materials on contact.',
    update: compose(createLiquidBehavior(35, 5), acidReaction),
    thermal: { conductivity: 0.050 },
  },
  {
    id: 7,
    key: 'lava',
    label: 'Lava',
    category: 'liquid',
    color: 0xff5a1a,
    colorVariance: 22,
    density: 80,
    hotkey: 'L',
    description: 'Molten rock at 110°. Ignites, melts, petrifies.',
    update: compose(createLiquidBehavior(80, 2), lavaReaction),
    thermal: {
      conductivity: 0.130,
      heatCapacity: 2.5,
      emitTemp: 110,
      emitStrength: 0.20,
      freezeAt: 40,
      freezesInto: 'stone',
    },
  },
  {
    id: 8,
    key: 'fire',
    label: 'Fire',
    category: 'special',
    color: 0xff8a1a,
    colorVariance: 30,
    density: 1,
    hotkey: 'F',
    description: 'Self-extinguishing heat at 90°. Spreads through flammables.',
    update: fireReaction,
    thermal: { conductivity: 0.150, heatCapacity: 0.5, emitTemp: 90, emitStrength: 0.25 },
  },
  {
    id: 9,
    key: 'smoke',
    label: 'Smoke',
    category: 'gas',
    color: 0x4a4a52,
    colorVariance: 10,
    density: 2,
    description: 'Rises and fades.',
    update: createGasBehavior({ density: 2, decayChance: 0.006 }),
    thermal: { conductivity: 0.015, heatCapacity: 0.3 },
  },
  {
    id: 10,
    key: 'steam',
    label: 'Steam',
    category: 'gas',
    color: 0xbfd9ff,
    colorVariance: 12,
    density: 3,
    description: 'Condenses back into water below 50°.',
    update: createGasBehavior({ density: 3, decayChance: 0.0015 }),
    thermal: { conductivity: 0.030, heatCapacity: 0.4, condenseAt: 50, condensesInto: 'water' },
  },
  {
    id: 11,
    key: 'gas',
    label: 'Gas',
    category: 'gas',
    color: 0xb8ff7a,
    colorVariance: 12,
    density: 4,
    flammable: true,
    burnChance: 0.9,
    hotkey: 'G',
    description: 'Explodes above 30°.',
    update: compose(
      createGasBehavior({ density: 4, decayChance: 0.002 }),
      explosiveReaction(6, 1),
    ),
    thermal: { conductivity: 0.015, ignitesAt: 30, explodeRadius: 6 },
  },
  {
    id: 12,
    key: 'wood',
    label: 'Wood',
    category: 'solid',
    color: 0x8a5a2a,
    colorVariance: 10,
    density: 700,
    flammable: true,
    burnChance: 0.15,
    description: 'Ignites above 75°.',
    thermal: { conductivity: 0.020, heatCapacity: 2.0, ignitesAt: 75 },
  },
  {
    id: 13,
    key: 'plant',
    label: 'Plant',
    category: 'solid',
    color: 0x3dc466,
    colorVariance: 20,
    density: 400,
    flammable: true,
    burnChance: 0.35,
    hotkey: 'P',
    description: 'Grows along water. Ignites above 45°.',
    update: plantReaction,
    thermal: { conductivity: 0.025, ignitesAt: 45 },
  },
  {
    id: 14,
    key: 'ice',
    label: 'Ice',
    category: 'solid',
    color: 0xaedcff,
    colorVariance: 10,
    density: 80,
    hotkey: 'I',
    description: 'Melts above 3°.',
    thermal: {
      conductivity: 0.080,
      heatCapacity: 2.0,
      emitTemp: -15,
      emitStrength: 0.10,
      meltAt: 3,
      meltsInto: 'water',
    },
  },
  {
    id: 15,
    key: 'glass',
    label: 'Glass',
    category: 'solid',
    color: 0xcfe9ff,
    colorVariance: 6,
    density: 850,
    description: 'Sand + lava.',
    thermal: { conductivity: 0.040, heatCapacity: 2.5 },
  },
  {
    id: 16,
    key: 'ash',
    label: 'Ash',
    category: 'powder',
    color: 0x3a3a42,
    colorVariance: 12,
    density: 40,
    description: 'Burnt remains.',
    update: createPowderBehavior(40),
    thermal: { conductivity: 0.020 },
  },
  {
    id: 17,
    key: 'salt',
    label: 'Salt',
    category: 'powder',
    color: 0xf0f0f5,
    colorVariance: 8,
    density: 55,
    description: 'Dissolves in water, melts ice.',
    update: compose(createPowderBehavior(55), saltReaction),
    thermal: { conductivity: 0.030 },
  },
  {
    id: 18,
    key: 'gunpowder',
    label: 'Gunpowder',
    category: 'powder',
    color: 0x1a1a20,
    colorVariance: 8,
    density: 55,
    flammable: true,
    burnChance: 1,
    description: 'Explodes above 50°.',
    update: compose(createPowderBehavior(55), explosiveReaction(5, 1)),
    thermal: { conductivity: 0.030, ignitesAt: 50, explodeRadius: 5 },
  },
  {
    id: 19,
    key: 'seed',
    label: 'Seed',
    category: 'powder',
    color: 0x6f4a1e,
    colorVariance: 12,
    density: 45,
    description: 'Sprouts into plant on water.',
    update: compose(createPowderBehavior(45), seedReaction),
    thermal: { conductivity: 0.025 },
  },
  {
    id: 20,
    key: 'spark',
    label: 'Spark',
    category: 'special',
    color: 0xffd84a,
    colorVariance: 20,
    density: 1,
    description: 'Single-tick igniter. Also energises conductors.',
    update: sparkReaction,
    thermal: { conductivity: 0.200, emitTemp: 60, emitStrength: 0.25 },
  },
  {
    id: 21,
    key: 'bomb',
    label: 'Bomb',
    category: 'solid',
    color: 0xc2302a,
    colorVariance: 8,
    density: 600,
    flammable: true,
    burnChance: 1,
    description: 'Huge explosion above 40°.',
    update: explosiveReaction(10, 1),
    thermal: { conductivity: 0.035, ignitesAt: 40, explodeRadius: 10 },
  },
  {
    id: 22,
    key: 'dust',
    label: 'Dust',
    category: 'powder',
    color: 0xbfa37a,
    colorVariance: 14,
    density: 25,
    flammable: true,
    burnChance: 0.6,
    description: 'Fine flammable particulate.',
    update: createPowderBehavior(25),
    thermal: { conductivity: 0.020, ignitesAt: 65 },
  },
  // ─── liquids ──────────────────────────────────────────────────────────
  {
    id: 23,
    key: 'napalm',
    label: 'Napalm',
    category: 'liquid',
    color: 0xc94a1a,
    colorVariance: 12,
    density: 25,
    flammable: true,
    burnChance: 0.9,
    description: 'Sticky liquid fire. Auto-ignites above 45°.',
    update: createLiquidBehavior(25, 2),
    thermal: { conductivity: 0.040, ignitesAt: 45 },
  },
  {
    id: 24,
    key: 'mercury',
    label: 'Mercury',
    category: 'liquid',
    color: 0xc4c9d4,
    colorVariance: 10,
    density: 500,
    description: 'Heavy silver liquid. Sinks through anything.',
    update: createLiquidBehavior(500, 3),
    thermal: { conductivity: 0.180 },
  },
  {
    id: 25,
    key: 'honey',
    label: 'Honey',
    category: 'liquid',
    color: 0xe0a924,
    colorVariance: 10,
    density: 55,
    flammable: true,
    burnChance: 0.1,
    description: 'Viscous sweet liquid. Barely flows.',
    update: createLiquidBehavior(55, 1),
    thermal: { conductivity: 0.020, ignitesAt: 85 },
  },
  {
    id: 26,
    key: 'slime',
    label: 'Slime',
    category: 'liquid',
    color: 0x6ad46a,
    colorVariance: 14,
    density: 40,
    description: 'Squishy and slow.',
    update: createLiquidBehavior(40, 1),
    thermal: { conductivity: 0.030 },
  },
  // ─── gases ────────────────────────────────────────────────────────────
  {
    id: 27,
    key: 'methane',
    label: 'Methane',
    category: 'gas',
    color: 0xd9ff9a,
    colorVariance: 10,
    density: 2,
    flammable: true,
    burnChance: 1,
    description: 'Very light. Detonates above 25°.',
    update: compose(
      createGasBehavior({ density: 2, decayChance: 0.0015, spread: 3 }),
      explosiveReaction(5, 1),
    ),
    thermal: { conductivity: 0.015, ignitesAt: 25, explodeRadius: 5 },
  },
  // ─── powders ──────────────────────────────────────────────────────────
  {
    id: 28,
    key: 'snow',
    label: 'Snow',
    category: 'powder',
    color: 0xf0f5ff,
    colorVariance: 8,
    density: 35,
    description: 'Melts to water above 1°.',
    update: createPowderBehavior(35),
    thermal: {
      conductivity: 0.060,
      emitTemp: -10,
      emitStrength: 0.10,
      meltAt: 1,
      meltsInto: 'water',
    },
  },
  {
    id: 29,
    key: 'mud',
    label: 'Mud',
    category: 'powder',
    color: 0x5c3a1e,
    colorVariance: 10,
    density: 70,
    description: 'Wet sand. Dries above 45°.',
    update: createPowderBehavior(70),
    thermal: { conductivity: 0.035, meltAt: 45, meltsInto: 'sand' },
  },
  {
    id: 30,
    key: 'virus',
    label: 'Virus',
    category: 'powder',
    color: 0x8a2aff,
    colorVariance: 30,
    density: 45,
    description: 'Infects plants and wood. Killed by fire / acid.',
    update: compose(createPowderBehavior(45), virusReaction),
    thermal: { conductivity: 0.025, ignitesAt: 55 },
  },
  {
    id: 31,
    key: 'nitro',
    label: 'Nitro',
    category: 'powder',
    color: 0xffd63a,
    colorVariance: 10,
    density: 50,
    flammable: true,
    burnChance: 1,
    description: 'Unstable. Massive explosion above 25°.',
    update: compose(createPowderBehavior(50), explosiveReaction(14, 1)),
    thermal: { conductivity: 0.040, ignitesAt: 25, explodeRadius: 14 },
  },
  // ─── solids ───────────────────────────────────────────────────────────
  {
    id: 32,
    key: 'copper',
    label: 'Copper',
    category: 'solid',
    color: 0xb2632a,
    colorVariance: 8,
    density: 900,
    description: 'Conducts electricity. Glows when charged. High heat conductivity.',
    update: conductorBehavior,
    renderColor: conductorRenderColor(0xb2632a, 0xfff1a8),
    thermal: { conductivity: 0.220, heatCapacity: 1.0 },
  },
  {
    id: 33,
    key: 'iron',
    label: 'Iron',
    category: 'solid',
    color: 0x7d7d86,
    colorVariance: 8,
    density: 910,
    description: 'Conductive, magnetic metal. Attracted by magnets.',
    update: conductorBehavior,
    renderColor: conductorRenderColor(0x7d7d86, 0xe8edff),
    thermal: { conductivity: 0.180, heatCapacity: 1.2 },
  },
  {
    id: 34,
    key: 'battery',
    label: 'Battery',
    category: 'solid',
    color: 0x24c275,
    colorVariance: 6,
    density: 900,
    description: 'Pulses electricity into adjacent copper / iron.',
    update: batteryBehavior,
    thermal: { conductivity: 0.050 },
  },
  {
    id: 35,
    key: 'magnet',
    label: 'Magnet',
    category: 'solid',
    color: 0x9c2a4a,
    colorVariance: 6,
    density: 950,
    description: 'Pulls iron toward itself within a radius.',
    update: magnetBehavior,
    thermal: { conductivity: 0.070 },
  },
  {
    id: 36,
    key: 'cloner',
    label: 'Cloner',
    category: 'solid',
    color: 0x3a7dff,
    colorVariance: 6,
    density: 1000,
    description: 'Duplicates the material next to it.',
    update: clonerBehavior,
    thermal: { conductivity: 0.010 },
  },
  {
    id: 37,
    key: 'void',
    label: 'Void',
    category: 'solid',
    color: 0x161821,
    colorVariance: 30,
    density: 1000,
    description: 'Annihilates anything touching it.',
    update: voidBehavior,
    thermal: { conductivity: 0.015, emitTemp: 0, emitStrength: 0.5 },
  },
  {
    id: 38,
    key: 'torch',
    label: 'Torch',
    category: 'solid',
    color: 0xff7a2a,
    colorVariance: 18,
    density: 1000,
    description: 'Persistent 120° heat source.',
    update: torchBehavior,
    thermal: { conductivity: 0.180, emitTemp: 120, emitStrength: 0.25 },
  },
  {
    id: 39,
    key: 'fan',
    label: 'Fan',
    category: 'solid',
    color: 0x2a9dc7,
    colorVariance: 6,
    density: 1000,
    description: 'Blows particles above it upward.',
    update: fanBehavior,
    thermal: { conductivity: 0.015 },
  },
  {
    id: 40,
    key: 'crystal',
    label: 'Crystal',
    category: 'solid',
    color: 0xa26dff,
    colorVariance: 22,
    density: 800,
    description: 'Grows where salt meets water.',
    update: crystalReaction,
    thermal: { conductivity: 0.060 },
  },
  {
    id: 41,
    key: 'uranium',
    label: 'Uranium',
    category: 'solid',
    color: 0x54ff6a,
    colorVariance: 14,
    density: 950,
    description:
      'Radioactive. Chain-reacts when clustered → nuclear detonation at 100°.',
    update: uraniumReaction,
    renderColor: pulseRenderColor(0x44a556, 0x9cff7a, 0.005),
    thermal: {
      conductivity: 0.100,
      emitTemp: 30,
      emitStrength: 0.15,
      ignitesAt: 100,
      explodeRadius: 20,
    },
  },
  {
    id: 42,
    key: 'fuse',
    label: 'Fuse',
    category: 'solid',
    color: 0x8a6a3a,
    colorVariance: 10,
    density: 700,
    flammable: true,
    burnChance: 1,
    description: 'Light it and watch the chain reaction travel.',
    thermal: { conductivity: 0.030, ignitesAt: 60 },
  },
  {
    id: 43,
    key: 'coal',
    label: 'Coal',
    category: 'solid',
    color: 0x181820,
    colorVariance: 8,
    density: 800,
    flammable: true,
    burnChance: 0.08,
    description: 'Slow, long-lasting burn.',
    thermal: { conductivity: 0.045, ignitesAt: 70 },
  },
  // ─── new additions for thermal play ──────────────────────────────────
  {
    id: 44,
    key: 'cryo',
    label: 'Cryo',
    category: 'liquid',
    color: 0x9de0ff,
    colorVariance: 18,
    density: 32,
    description: 'Liquid nitrogen. Freezes everything nearby.',
    update: createLiquidBehavior(32, 4),
    thermal: {
      conductivity: 0.180,
      heatCapacity: 2.5,
      emitTemp: -80,
      emitStrength: 0.20,
      boilAt: -40,
      boilsInto: 'steam',
    },
  },
  {
    id: 45,
    key: 'thermite',
    label: 'Thermite',
    category: 'powder',
    color: 0xd4a32a,
    colorVariance: 12,
    density: 65,
    flammable: true,
    burnChance: 1,
    description: 'Ignites above 70° and burns at 120°.',
    update: createPowderBehavior(65),
    thermal: { conductivity: 0.070, ignitesAt: 70 },
  },
  // ─── exotic ──────────────────────────────────────────────────────────
  {
    id: 46,
    key: 'radiation',
    label: 'Radiation',
    category: 'special',
    color: 0xb6ff88,
    colorVariance: 0,
    density: 1,
    description: 'Directional projectile. Mutates what it touches.',
    update: radiationBehavior,
    thermal: { conductivity: 0.040 },
  },
  {
    id: 47,
    key: 'blackhole',
    label: 'Black Hole',
    category: 'solid',
    color: 0x050508,
    colorVariance: 18,
    density: 10000,
    description: 'Pulls everything nearby into the event horizon.',
    update: blackHoleBehavior,
    renderColor: pulseRenderColor(0x050508, 0x1a0a30, 0.002),
    thermal: { conductivity: 0.020 },
  },
  {
    id: 48,
    key: 'portal_a',
    label: 'Portal A',
    category: 'solid',
    color: 0x3a66ff,
    colorVariance: 6,
    density: 1000,
    description: 'Teleports adjacent cells to a random Portal B.',
    update: portalABehavior,
    renderColor: pulseRenderColor(0x3a66ff, 0x8ab4ff, 0.008),
    thermal: { conductivity: 0.040 },
  },
  {
    id: 49,
    key: 'portal_b',
    label: 'Portal B',
    category: 'solid',
    color: 0xff3a88,
    colorVariance: 6,
    density: 1000,
    description: 'Teleports adjacent cells to a random Portal A.',
    update: portalBBehavior,
    renderColor: pulseRenderColor(0xff3a88, 0xffa0c8, 0.008),
    thermal: { conductivity: 0.040 },
  },
  {
    id: 50,
    key: 'antigravity',
    label: 'Antigrav',
    category: 'solid',
    color: 0x24e6ff,
    colorVariance: 10,
    density: 1000,
    description: 'Column of cells above is pushed upward.',
    update: antigravityBehavior,
    thermal: { conductivity: 0.020 },
  },
  {
    id: 51,
    key: 'lightning_rod',
    label: 'Rod',
    category: 'solid',
    color: 0xc0b86a,
    colorVariance: 8,
    density: 900,
    description: 'Calls a lightning bolt from the sky every few seconds.',
    update: lightningRodBehavior,
    thermal: { conductivity: 0.180 },
  },
  {
    id: 52,
    key: 'foam',
    label: 'Foam',
    category: 'liquid',
    color: 0xe5f5ff,
    colorVariance: 8,
    density: 10,
    description: 'Floaty soap foam. Pops in fire.',
    update: createLiquidBehavior(10, 3),
    thermal: { conductivity: 0.005, ignitesAt: 60 },
  },
  {
    id: 53,
    key: 'glue',
    label: 'Glue',
    category: 'solid',
    color: 0xf0e3a8,
    colorVariance: 8,
    density: 1000,
    description: 'Pins adjacent powder/liquid cells in place.',
    update: glueBehavior,
    thermal: { conductivity: 0.015 },
  },
  // ─── atmospheric gases ────────────────────────────────────────────────
  {
    id: 54,
    key: 'oxygen',
    label: 'Oxygen',
    category: 'gas',
    color: 0xd5ecff,
    colorVariance: 6,
    density: 1,
    flammable: true,
    burnChance: 0.6,
    description: 'Fuels fire — extends lifespan of adjacent flames.',
    update: compose(
      createGasBehavior({ density: 1, decayChance: 0.0005, spread: 3 }),
      oxygenBehavior,
    ),
    thermal: { conductivity: 0.010, ignitesAt: 150 },
  },
  {
    id: 55,
    key: 'co2',
    label: 'CO₂',
    category: 'gas',
    color: 0x6a6a74,
    colorVariance: 6,
    density: 7,
    description: 'Smothers fire on contact.',
    update: compose(createGasBehavior({ density: 7, decayChance: 0.002 }), co2Behavior),
    thermal: { conductivity: 0.015 },
  },
  {
    id: 56,
    key: 'chlorine',
    label: 'Chlorine',
    category: 'gas',
    color: 0xbaff5a,
    colorVariance: 12,
    density: 9,
    description: 'Toxic. Destroys plants, seeds, mushrooms.',
    update: compose(createGasBehavior({ density: 9, decayChance: 0.0015 }), chlorineBehavior),
    thermal: { conductivity: 0.015 },
  },
  {
    id: 57,
    key: 'helium',
    label: 'Helium',
    category: 'gas',
    color: 0xffe6ff,
    colorVariance: 8,
    density: 0,
    description: 'Lighter than everything. Rises very fast.',
    update: createGasBehavior({ density: 0, decayChance: 0.0005, spread: 4 }),
    thermal: { conductivity: 0.020 },
  },
  // ─── exotic matter ────────────────────────────────────────────────────
  {
    id: 58,
    key: 'antimatter',
    label: 'Antimatter',
    category: 'solid',
    color: 0xff1a88,
    colorVariance: 24,
    density: 900,
    description: 'Annihilates on contact. Do not breathe near it.',
    update: antimatterBehavior,
    renderColor: pulseRenderColor(0xff1a88, 0xffc8e8, 0.006),
    thermal: { conductivity: 0.080, emitTemp: 40, emitStrength: 0.15 },
  },
  {
    id: 59,
    key: 'ice9',
    label: 'Ice-9',
    category: 'solid',
    color: 0xd8e8ff,
    colorVariance: 8,
    density: 85,
    description: 'Crystallises every drop of water it touches.',
    update: ice9Behavior,
    thermal: {
      conductivity: 0.100,
      emitTemp: -20,
      emitStrength: 0.10,
      meltAt: 20,
      meltsInto: 'water',
    },
  },
  {
    id: 60,
    key: 'lightningcloud',
    label: 'Storm Cloud',
    category: 'gas',
    color: 0x3a3a50,
    colorVariance: 16,
    density: 4,
    description: 'Drifts and periodically discharges a downward spark.',
    update: compose(
      createGasBehavior({ density: 4, decayChance: 0 }),
      lightningCloudBehavior,
    ),
    thermal: { conductivity: 0.015 },
  },
  {
    id: 61,
    key: 'mushroom',
    label: 'Mushroom',
    category: 'solid',
    color: 0xd56a8a,
    colorVariance: 20,
    density: 350,
    flammable: true,
    burnChance: 0.3,
    description: 'Spreads across ash / mud where moisture is near.',
    update: mushroomBehavior,
    thermal: { conductivity: 0.030, ignitesAt: 50 },
  },
  {
    id: 62,
    key: 'nanobots',
    label: 'Nanobots',
    category: 'powder',
    color: 0xa0a8b8,
    colorVariance: 16,
    density: 55,
    description: 'Consume neighbours and replicate. Contain carefully.',
    update: compose(createPowderBehavior(55), nanobotBehavior),
    thermal: { conductivity: 0.070, ignitesAt: 120 },
  },
  {
    id: 63,
    key: 'tar',
    label: 'Tar',
    category: 'liquid',
    color: 0x1a1018,
    colorVariance: 10,
    density: 45,
    flammable: true,
    burnChance: 0.4,
    description: 'Heavy, slow, burns long.',
    update: createLiquidBehavior(45, 1),
    thermal: { conductivity: 0.020, ignitesAt: 70 },
  },
  {
    id: 64,
    key: 'poison',
    label: 'Poison',
    category: 'liquid',
    color: 0x7a2aff,
    colorVariance: 14,
    density: 28,
    description: 'Kills plants and mushrooms; slowly contaminates water.',
    update: compose(createLiquidBehavior(28, 4), poisonReaction),
    thermal: { conductivity: 0.040 },
  },
  {
    id: 65,
    key: 'rubber',
    label: 'Rubber',
    category: 'solid',
    color: 0x402a36,
    colorVariance: 8,
    density: 600,
    flammable: true,
    burnChance: 0.1,
    description: 'Electrical insulator. Burns slowly.',
    thermal: { conductivity: 0.003, ignitesAt: 95 },
  },
  {
    id: 66,
    key: 'geyser',
    label: 'Geyser',
    category: 'solid',
    color: 0x4a7896,
    colorVariance: 10,
    density: 1000,
    description: 'Erupts a column of steam and water every few seconds.',
    update: geyserBehavior,
    thermal: { conductivity: 0.080, emitTemp: 50, emitStrength: 0.10 },
  },
  {
    id: 67,
    key: 'obsidian',
    label: 'Obsidian',
    category: 'solid',
    color: 0x14101c,
    colorVariance: 14,
    density: 930,
    description: 'Volcanic glass. Nearly indestructible.',
    thermal: { conductivity: 0.040 },
  },
  {
    id: 68,
    key: 'diamond',
    label: 'Diamond',
    category: 'solid',
    color: 0xcdf0ff,
    colorVariance: 24,
    density: 1000,
    description: 'Hardest solid. Conducts heat, resists everything.',
    thermal: { conductivity: 0.150 },
  },
  {
    id: 69,
    key: 'wax',
    label: 'Wax',
    category: 'solid',
    color: 0xf0e0a0,
    colorVariance: 10,
    density: 600,
    flammable: true,
    burnChance: 0.2,
    description: 'Melts above 50° into wax liquid.',
    thermal: { conductivity: 0.020, meltAt: 50, meltsInto: 'waxliq', ignitesAt: 90 },
  },
  {
    id: 70,
    key: 'waxliq',
    label: 'Wax Liquid',
    category: 'liquid',
    color: 0xf5eab0,
    colorVariance: 8,
    density: 35,
    flammable: true,
    burnChance: 0.15,
    description: 'Molten wax. Hardens below 30°.',
    update: createLiquidBehavior(35, 2),
    thermal: { conductivity: 0.025, freezeAt: 30, freezesInto: 'wax', ignitesAt: 85 },
  },
  {
    id: 71,
    key: 'wick',
    label: 'Wick',
    category: 'solid',
    color: 0xe8d79a,
    colorVariance: 10,
    density: 500,
    flammable: true,
    burnChance: 0.5,
    description: 'Absorbs wax and burns steadily.',
    thermal: { conductivity: 0.030, ignitesAt: 60 },
  },
];

export const registerAllElements = (): void => {
  for (const d of defs) registerElement(d);
};
